// -------------------------------------------------------------
// 
// File Name: A:\internship\MATLAB\DELAY\DELAY\DELAY.v
// Created: 2022-12-13 22:21:21
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// X_n_1                         ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DELAY
// Source Path: DELAY/DELAY
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DELAY
          (clk,
           reset,
           clk_enable,
           X_n,
           ce_out,
           X_n_1);


  input   clk;
  input   reset;
  input   clk_enable;
  input   [7:0] X_n;  // uint8
  output  ce_out;
  output  [7:0] X_n_1;  // uint8


  wire enb;
  reg [7:0] Delay_out1;  // uint8


  assign enb = clk_enable;

  always @(posedge clk or posedge reset)
    begin : Delay_1_process
      if (reset == 1'b1) begin
        Delay_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= X_n;
        end
      end
    end



  assign X_n_1 = Delay_out1;

  assign ce_out = clk_enable;

endmodule  // DELAY

