// -------------------------------------------------------------
// 
// File Name: A:\internship\MATLAB\BLOCK_SEVEN_TAP_FILTER\BLOCK_SEVEN_TAP_FILTER\BLOCK_SEVEN_TAP_FILTER_tb.v
// Created: 2022-12-13 23:59:51
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Y                             ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BLOCK_SEVEN_TAP_FILTER_tb
// Source Path: 
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BLOCK_SEVEN_TAP_FILTER_tb;



  reg  clk;
  reg  reset;
  wire clk_enable;
  wire [7:0] rawData_h0;  // uint8
  wire [7:0] rawData_h1;  // uint8
  wire [7:0] rawData_h2;  // uint8
  wire [7:0] rawData_h3;  // uint8
  wire [7:0] rawData_h4;  // uint8
  wire [7:0] rawData_h5;  // uint8
  wire [7:0] rawData_h6;  // uint8
  wire Y_done;  // ufix1
  wire rdEnb;
  wire Y_done_enb;  // ufix1
  reg [3:0] Y_addr;  // ufix4
  wire Y_active;  // ufix1
  reg [3:0] Constant_out1_addr;  // ufix4
  wire Constant_out1_active;  // ufix1
  reg  tb_enb_delay;
  wire Constant_out1_enb;  // ufix1
  wire [3:0] Discrete_Impulse_out1_addr_delay_1;  // ufix4
  reg signed [31:0] fp_X;  // sfix32
  reg [7:0] rawData_X;  // uint8
  reg signed [31:0] status_X;  // sfix32
  reg [7:0] holdData_X;  // uint8
  reg [7:0] X_offset;  // uint8
  wire [7:0] X;  // uint8
  reg [7:0] holdData_h6;  // uint8
  reg [7:0] h6_offset;  // uint8
  wire [7:0] h6_1;  // uint8
  reg [7:0] holdData_h5;  // uint8
  reg [7:0] h5_offset;  // uint8
  wire [7:0] h5_1;  // uint8
  reg [7:0] holdData_h4;  // uint8
  reg [7:0] h4_offset;  // uint8
  wire [7:0] h4_1;  // uint8
  reg [7:0] holdData_h3;  // uint8
  reg [7:0] h3_offset;  // uint8
  wire [7:0] h3_1;  // uint8
  reg [7:0] holdData_h2;  // uint8
  reg [7:0] h2_offset;  // uint8
  wire [7:0] h2_1;  // uint8
  reg [7:0] holdData_h1;  // uint8
  reg [7:0] h1_offset;  // uint8
  wire [7:0] h1_1;  // uint8
  reg [7:0] holdData_h0;  // uint8
  reg [7:0] h0_offset;  // uint8
  wire [7:0] h0_1;  // uint8
  reg  check1_done;  // ufix1
  wire snkDonen;
  wire resetn;
  wire tb_enb;
  wire ce_out;
  wire [7:0] Y;  // uint8
  wire Y_enb;  // ufix1
  wire Y_lastAddr;  // ufix1
  wire [3:0] Y_addr_delay_1;  // ufix4
  reg signed [31:0] fp_Y_expected;  // sfix32
  reg [7:0] Y_expected;  // uint8
  reg signed [31:0] status_Y_expected;  // sfix32
  wire [7:0] Y_ref;  // uint8
  reg  Y_testFailure;  // ufix1
  wire testFailure;  // ufix1

  function real absReal(input real num);
  begin
    if (num < 0)
      absReal = -num;
    else
      absReal = num;
  end
  endfunction

  function real floatHalfToReal;
  input [15:0] x;
  reg [63:0] conv;

  begin
    conv[63] = x[15]; // sign 
    if (x[14:10] == 5'b0) // exp 
      conv[62:52] = 11'b0; 
    else
      conv[62:52] = 1023 + (x[14:10] - 15);
    conv[51:42] = x[9:0]; // mantissa 
    conv[41:0] = 42'b0;
    if (((x[14:10] == 5'h1F) && (x[9:0] != 10'h0))) // check for NaN 
    begin
      conv[63] = 1'b0;
      conv[62:52] = 11'h7FF;
      conv[51:0] = 52'h0;
    end
    floatHalfToReal = $bitstoreal(conv);
  end
  endfunction

  function real floatSingleToReal;
  input [31:0] x;
  reg [63:0] conv;

  begin
    conv[63] = x[31]; // sign 
    if (x[30:23] == 8'b0) // exp 
      conv[62:52] = 11'b0; 
    else
      conv[62:52] = 1023 + (x[30:23] - 127);
    conv[51:29] = x[22:0]; // mantissa 
    conv[28:0] = 29'b0;
    if (((x[30:23] == 8'hFF) && (x[22:0] != 23'h0))) // check for NaN 
    begin
      conv[63] = 1'b0;
      conv[62:52] = 11'h7FF;
      conv[51:0] = 52'h0;
    end
    floatSingleToReal = $bitstoreal(conv);
  end
  endfunction

  function real floatDoubleToReal;
  input [63:0] x;
  reg [63:0] conv;

  begin
    conv[63:0] = x[63:0]; 
    if (((x[62:52] == 11'h7FF) && (x[51:0] != 52'h0))) // check for NaN 
    begin
      conv[63] = 1'b0;
      conv[62:52] = 11'h7FF;
      conv[51:0] = 52'h0;
    end
    floatDoubleToReal = $bitstoreal(conv);
  end
  endfunction

  function isFloatEpsEqual(input real a, input real b, input real eps);
  real absdiff;

  begin
    absdiff = absReal(a - b);
    if (absdiff < eps) // absolute error check 
      isFloatEpsEqual = 1;
    else if (a == b) // check infinities 
      isFloatEpsEqual = 1; 
    else if (a*b == 0.0) // either is zero 
      isFloatEpsEqual = (absdiff < eps);
    else if (absReal(a) < absReal(b)) // relative error check
      isFloatEpsEqual = absdiff/absReal(b) < eps;
    else
      isFloatEpsEqual = absdiff/absReal(a) < eps;
  end
  endfunction
  function isFloatHalfEpsEqual;
  input [15:0] x;
  input [15:0] y;
  input real eps;
  real a, b;
  real absdiff;

  begin
    a = floatHalfToReal(x);
    b = floatHalfToReal(y);
    isFloatHalfEpsEqual = isFloatEpsEqual(a, b, eps);
  end
  endfunction
  function isFloatSingleEpsEqual;
  input [31:0] x;
  input [31:0] y;
  input real eps;
  real a, b;
  real absdiff;

  begin
    a = floatSingleToReal(x);
    b = floatSingleToReal(y);
    isFloatSingleEpsEqual = isFloatEpsEqual(a, b, eps);
  end
  endfunction
  function isFloatDoubleEpsEqual;
  input [63:0] x;
  input [63:0] y;
  input real eps;
  real a, b;
  real absdiff;

  begin
    a = floatDoubleToReal(x);
    b = floatDoubleToReal(y);
    isFloatDoubleEpsEqual = isFloatEpsEqual(a, b, eps);
  end
  endfunction

  // Data source for h0
  assign rawData_h0 = 8'b00000001;



  // Data source for h1
  assign rawData_h1 = 8'b00000001;



  // Data source for h2
  assign rawData_h2 = 8'b00000001;



  // Data source for h3
  assign rawData_h3 = 8'b00000000;



  // Data source for h4
  assign rawData_h4 = 8'b00000001;



  // Data source for h5
  assign rawData_h5 = 8'b00000001;



  // Data source for h6
  assign rawData_h6 = 8'b00000001;



  assign Y_done_enb = Y_done & rdEnb;



  assign Y_active = Y_addr != 4'b1010;



  assign Constant_out1_active = Constant_out1_addr != 4'b1010;



  assign Constant_out1_enb = Constant_out1_active & (rdEnb & tb_enb_delay);



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 10
  always @(posedge clk or posedge reset)
    begin : Constant_process
      if (reset == 1'b1) begin
        Constant_out1_addr <= 4'b0000;
      end
      else begin
        if (Constant_out1_enb) begin
          if (Constant_out1_addr >= 4'b1010) begin
            Constant_out1_addr <= 4'b0000;
          end
          else begin
            Constant_out1_addr <= Constant_out1_addr + 4'b0001;
          end
        end
      end
    end



  assign #1 Discrete_Impulse_out1_addr_delay_1 = Constant_out1_addr;

  // Data source for X
  initial
    begin : X_fileread
      fp_X = $fopen("X.dat", "r");
      status_X = $rewind(fp_X);
    end

  always @(Discrete_Impulse_out1_addr_delay_1, rdEnb, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        rawData_X <= 8'bx;
      end
      else if (rdEnb == 1) begin
        status_X = $fscanf(fp_X, "%h", rawData_X);
      end
    end

  // holdData reg for Discrete_Impulse_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Discrete_Impulse_out1
      if (reset) begin
        holdData_X <= 8'bx;
      end
      else begin
        holdData_X <= rawData_X;
      end
    end

  always @(rawData_X or rdEnb)
    begin : stimuli_Discrete_Impulse_out1_1
      if (rdEnb == 1'b0) begin
        X_offset <= holdData_X;
      end
      else begin
        X_offset <= rawData_X;
      end
    end

  assign #2 X = X_offset;

  // holdData reg for Constant6_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Constant6_out1
      if (reset) begin
        holdData_h6 <= 8'bx;
      end
      else begin
        holdData_h6 <= rawData_h6;
      end
    end

  always @(rawData_h6 or rdEnb)
    begin : stimuli_Constant6_out1_1
      if (rdEnb == 1'b0) begin
        h6_offset <= holdData_h6;
      end
      else begin
        h6_offset <= rawData_h6;
      end
    end

  assign #2 h6_1 = h6_offset;

  // holdData reg for Constant5_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Constant5_out1
      if (reset) begin
        holdData_h5 <= 8'bx;
      end
      else begin
        holdData_h5 <= rawData_h5;
      end
    end

  always @(rawData_h5 or rdEnb)
    begin : stimuli_Constant5_out1_1
      if (rdEnb == 1'b0) begin
        h5_offset <= holdData_h5;
      end
      else begin
        h5_offset <= rawData_h5;
      end
    end

  assign #2 h5_1 = h5_offset;

  // holdData reg for Constant4_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Constant4_out1
      if (reset) begin
        holdData_h4 <= 8'bx;
      end
      else begin
        holdData_h4 <= rawData_h4;
      end
    end

  always @(rawData_h4 or rdEnb)
    begin : stimuli_Constant4_out1_1
      if (rdEnb == 1'b0) begin
        h4_offset <= holdData_h4;
      end
      else begin
        h4_offset <= rawData_h4;
      end
    end

  assign #2 h4_1 = h4_offset;

  // holdData reg for Constant3_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Constant3_out1
      if (reset) begin
        holdData_h3 <= 8'bx;
      end
      else begin
        holdData_h3 <= rawData_h3;
      end
    end

  always @(rawData_h3 or rdEnb)
    begin : stimuli_Constant3_out1_1
      if (rdEnb == 1'b0) begin
        h3_offset <= holdData_h3;
      end
      else begin
        h3_offset <= rawData_h3;
      end
    end

  assign #2 h3_1 = h3_offset;

  // holdData reg for Constant2_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Constant2_out1
      if (reset) begin
        holdData_h2 <= 8'bx;
      end
      else begin
        holdData_h2 <= rawData_h2;
      end
    end

  always @(rawData_h2 or rdEnb)
    begin : stimuli_Constant2_out1_1
      if (rdEnb == 1'b0) begin
        h2_offset <= holdData_h2;
      end
      else begin
        h2_offset <= rawData_h2;
      end
    end

  assign #2 h2_1 = h2_offset;

  // holdData reg for Constant1_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Constant1_out1
      if (reset) begin
        holdData_h1 <= 8'bx;
      end
      else begin
        holdData_h1 <= rawData_h1;
      end
    end

  always @(rawData_h1 or rdEnb)
    begin : stimuli_Constant1_out1_1
      if (rdEnb == 1'b0) begin
        h1_offset <= holdData_h1;
      end
      else begin
        h1_offset <= rawData_h1;
      end
    end

  assign #2 h1_1 = h1_offset;

  // holdData reg for Constant_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Constant_out1
      if (reset) begin
        holdData_h0 <= 8'bx;
      end
      else begin
        holdData_h0 <= rawData_h0;
      end
    end

  always @(rawData_h0 or rdEnb)
    begin : stimuli_Constant_out1_1
      if (rdEnb == 1'b0) begin
        h0_offset <= holdData_h0;
      end
      else begin
        h0_offset <= rawData_h0;
      end
    end

  assign #2 h0_1 = h0_offset;

  assign snkDonen =  ~ check1_done;



  assign resetn =  ~ reset;



  assign tb_enb = resetn & snkDonen;



  // Delay inside enable generation: register depth 1
  always @(posedge clk or posedge reset)
    begin : u_enable_delay
      if (reset) begin
        tb_enb_delay <= 0;
      end
      else begin
        tb_enb_delay <= tb_enb;
      end
    end

  assign rdEnb = (check1_done == 1'b0 ? tb_enb_delay :
              1'b0);



  assign #2 clk_enable = rdEnb;

  initial
    begin : reset_gen
      reset <= 1'b1;
      # (20);
      @ (posedge clk)
      # (2);
      reset <= 1'b0;
    end

  always 
    begin : clk_gen
      clk <= 1'b1;
      # (5);
      clk <= 1'b0;
      # (5);
      if (check1_done == 1'b1) begin
        clk <= 1'b1;
        # (5);
        clk <= 1'b0;
        # (5);
        $stop;
      end
    end

  BLOCK_SEVEN_TAP_FILTER u_BLOCK_SEVEN_TAP_FILTER (.clk(clk),
                                                   .reset(reset),
                                                   .clk_enable(clk_enable),
                                                   .h0(h0_1),  // uint8
                                                   .h1(h1_1),  // uint8
                                                   .h2(h2_1),  // uint8
                                                   .h3(h3_1),  // uint8
                                                   .h4(h4_1),  // uint8
                                                   .h5(h5_1),  // uint8
                                                   .h6(h6_1),  // uint8
                                                   .X(X),  // uint8
                                                   .ce_out(ce_out),
                                                   .Y(Y)  // uint8
                                                   );

  assign Y_enb = ce_out & Y_active;



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 10
  always @(posedge clk or posedge reset)
    begin : c_2_process
      if (reset == 1'b1) begin
        Y_addr <= 4'b0000;
      end
      else begin
        if (Y_enb) begin
          if (Y_addr >= 4'b1010) begin
            Y_addr <= 4'b0000;
          end
          else begin
            Y_addr <= Y_addr + 4'b0001;
          end
        end
      end
    end



  assign Y_lastAddr = Y_addr >= 4'b1010;



  assign Y_done = Y_lastAddr & resetn;



  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_1
      if (reset) begin
        check1_done <= 0;
      end
      else begin
        if (Y_done_enb) begin
          check1_done <= Y_done;
        end
      end
    end

  assign #1 Y_addr_delay_1 = Y_addr;

  // Data source for Y_expected
  initial
    begin : Y_expected_fileread
      fp_Y_expected = $fopen("Y_expected.dat", "r");
      status_Y_expected = $rewind(fp_Y_expected);
    end

  always @(Y_addr_delay_1, ce_out, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        Y_expected <= 8'bx;
      end
      else if (ce_out == 1) begin
        status_Y_expected = $fscanf(fp_Y_expected, "%h", Y_expected);
      end
    end

  assign Y_ref = Y_expected;

  always @(posedge clk or posedge reset)
    begin : Y_checker
      if (reset == 1'b1) begin
        Y_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && Y !== Y_ref) begin
          Y_testFailure <= 1'b1;
          $display("ERROR in Y at time %t : Expected '%h' Actual '%h'", $time, Y_ref, Y);
        end
      end
    end

  assign testFailure = Y_testFailure;

  always @(posedge clk)
    begin : completed_msg
      if (check1_done == 1'b1) begin
        if (testFailure == 1'b0) begin
          $display("**************TEST COMPLETED (PASSED)**************");
        end
        else begin
          $display("**************TEST COMPLETED (FAILED)**************");
        end
      end
    end

endmodule  // BLOCK_SEVEN_TAP_FILTER_tb

