// -------------------------------------------------------------
// 
// File Name: A:\internship\MATLAB\BLOCK_SEVEN_TAP_FILTER\BLOCK_SEVEN_TAP_FILTER\DELAY5.v
// Created: 2022-12-13 23:58:48
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DELAY5
// Source Path: BLOCK_SEVEN_TAP_FILTER/BLOCK_SEVEN_TAP_FILTER/DELAY5
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DELAY5
          (clk,
           reset,
           enb,
           X_n,
           X_n_1);


  input   clk;
  input   reset;
  input   enb;
  input   [7:0] X_n;  // uint8
  output  [7:0] X_n_1;  // uint8


  reg [7:0] Delay_out1;  // uint8


  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= X_n;
        end
      end
    end



  assign X_n_1 = Delay_out1;

endmodule  // DELAY5

