// -------------------------------------------------------------
// 
// File Name: A:\internship\MATLAB\BLOCK_SEVEN_TAP_FILTER\BLOCK_SEVEN_TAP_FILTER\MUL3.v
// Created: 2022-12-13 23:58:48
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: MUL3
// Source Path: BLOCK_SEVEN_TAP_FILTER/BLOCK_SEVEN_TAP_FILTER/MUL3
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module MUL3
          (A,
           B,
           Y);


  input   [7:0] A;  // uint8
  input   [7:0] B;  // uint8
  output  [7:0] Y;  // uint8


  wire [15:0] Product_mul_temp;  // ufix16
  wire [7:0] Product_out1;  // uint8


  assign Product_mul_temp = A * B;
  assign Product_out1 = Product_mul_temp[7:0];



  assign Y = Product_out1;

endmodule  // MUL3

