// -------------------------------------------------------------
// 
// File Name: C:\Users\saran\Desktop\TWO_TAP_FILTER_VERILOG\TWO_BIT_ADDER_VERILOG\TWO_BIT_ADDER\TWO_BIT_ADDER\TWO_BIT_ADDER.v
// Created: 2022-12-12 11:31:30
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Y                             ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: TWO_BIT_ADDER
// Source Path: TWO_BIT_ADDER/TWO_BIT_ADDER
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module TWO_BIT_ADDER
          (clk,
           reset,
           clk_enable,
           In1,
           In2,
           ce_out,
           Y);


  input   clk;
  input   reset;
  input   clk_enable;
  input   [63:0] In1;  // double
  input   [63:0] In2;  // double
  output  ce_out;
  output  [63:0] Y;  // double


  wire [63:0] Sum_out1;  // ufix64


  nfp_add_double u_nfp_add_comp (.clk(clk),
                                 .reset(reset),
                                 .enb(clk_enable),
                                 .nfp_in1(In1),  // double
                                 .nfp_in2(In2),  // double
                                 .nfp_out(Sum_out1)  // double
                                 );

  assign ce_out = clk_enable;

  assign Y = Sum_out1;

endmodule  // TWO_BIT_ADDER

