// -------------------------------------------------------------
// 
// File Name: A:\internship\MATLAB\DELAY\DELAY\DELAY_tb.v
// Created: 2022-12-13 22:23:01
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// X_n_1                         ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DELAY_tb
// Source Path: 
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DELAY_tb;



  reg  clk;
  reg  reset;
  wire clk_enable;
  wire [7:0] rawData_X_n;  // uint8
  wire X_n_1_done;  // ufix1
  wire rdEnb;
  wire X_n_1_done_enb;  // ufix1
  reg [3:0] X_n_1_addr;  // ufix4
  wire X_n_1_active;  // ufix1
  reg [7:0] holdData_X_n;  // uint8
  reg [7:0] X_n_offset;  // uint8
  wire [7:0] X_n_1;  // uint8
  reg  check1_done;  // ufix1
  wire snkDonen;
  wire resetn;
  wire tb_enb;
  reg  tb_enb_delay;
  wire ce_out;
  wire [7:0] X_n_1_1;  // uint8
  wire X_n_1_enb;  // ufix1
  wire X_n_1_lastAddr;  // ufix1
  wire [3:0] X_n_1_addr_delay_1;  // ufix4
  reg signed [31:0] fp_X_n_1_expected;  // sfix32
  reg [7:0] X_n_1_expected;  // uint8
  reg signed [31:0] status_X_n_1_expected;  // sfix32
  wire [7:0] X_n_1_ref;  // uint8
  reg  X_n_1_testFailure;  // ufix1
  wire testFailure;  // ufix1

  function real absReal(input real num);
  begin
    if (num < 0)
      absReal = -num;
    else
      absReal = num;
  end
  endfunction

  function real floatHalfToReal;
  input [15:0] x;
  reg [63:0] conv;

  begin
    conv[63] = x[15]; // sign 
    if (x[14:10] == 5'b0) // exp 
      conv[62:52] = 11'b0; 
    else
      conv[62:52] = 1023 + (x[14:10] - 15);
    conv[51:42] = x[9:0]; // mantissa 
    conv[41:0] = 42'b0;
    if (((x[14:10] == 5'h1F) && (x[9:0] != 10'h0))) // check for NaN 
    begin
      conv[63] = 1'b0;
      conv[62:52] = 11'h7FF;
      conv[51:0] = 52'h0;
    end
    floatHalfToReal = $bitstoreal(conv);
  end
  endfunction

  function real floatSingleToReal;
  input [31:0] x;
  reg [63:0] conv;

  begin
    conv[63] = x[31]; // sign 
    if (x[30:23] == 8'b0) // exp 
      conv[62:52] = 11'b0; 
    else
      conv[62:52] = 1023 + (x[30:23] - 127);
    conv[51:29] = x[22:0]; // mantissa 
    conv[28:0] = 29'b0;
    if (((x[30:23] == 8'hFF) && (x[22:0] != 23'h0))) // check for NaN 
    begin
      conv[63] = 1'b0;
      conv[62:52] = 11'h7FF;
      conv[51:0] = 52'h0;
    end
    floatSingleToReal = $bitstoreal(conv);
  end
  endfunction

  function real floatDoubleToReal;
  input [63:0] x;
  reg [63:0] conv;

  begin
    conv[63:0] = x[63:0]; 
    if (((x[62:52] == 11'h7FF) && (x[51:0] != 52'h0))) // check for NaN 
    begin
      conv[63] = 1'b0;
      conv[62:52] = 11'h7FF;
      conv[51:0] = 52'h0;
    end
    floatDoubleToReal = $bitstoreal(conv);
  end
  endfunction

  function isFloatEpsEqual(input real a, input real b, input real eps);
  real absdiff;

  begin
    absdiff = absReal(a - b);
    if (absdiff < eps) // absolute error check 
      isFloatEpsEqual = 1;
    else if (a == b) // check infinities 
      isFloatEpsEqual = 1; 
    else if (a*b == 0.0) // either is zero 
      isFloatEpsEqual = (absdiff < eps);
    else if (absReal(a) < absReal(b)) // relative error check
      isFloatEpsEqual = absdiff/absReal(b) < eps;
    else
      isFloatEpsEqual = absdiff/absReal(a) < eps;
  end
  endfunction
  function isFloatHalfEpsEqual;
  input [15:0] x;
  input [15:0] y;
  input real eps;
  real a, b;
  real absdiff;

  begin
    a = floatHalfToReal(x);
    b = floatHalfToReal(y);
    isFloatHalfEpsEqual = isFloatEpsEqual(a, b, eps);
  end
  endfunction
  function isFloatSingleEpsEqual;
  input [31:0] x;
  input [31:0] y;
  input real eps;
  real a, b;
  real absdiff;

  begin
    a = floatSingleToReal(x);
    b = floatSingleToReal(y);
    isFloatSingleEpsEqual = isFloatEpsEqual(a, b, eps);
  end
  endfunction
  function isFloatDoubleEpsEqual;
  input [63:0] x;
  input [63:0] y;
  input real eps;
  real a, b;
  real absdiff;

  begin
    a = floatDoubleToReal(x);
    b = floatDoubleToReal(y);
    isFloatDoubleEpsEqual = isFloatEpsEqual(a, b, eps);
  end
  endfunction

  // Data source for X_n
  assign rawData_X_n = 8'b00000001;



  assign X_n_1_done_enb = X_n_1_done & rdEnb;



  assign X_n_1_active = X_n_1_addr != 4'b1010;



  // holdData reg for Constant_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Constant_out1
      if (reset) begin
        holdData_X_n <= 8'bx;
      end
      else begin
        holdData_X_n <= rawData_X_n;
      end
    end

  always @(rawData_X_n or rdEnb)
    begin : stimuli_Constant_out1_1
      if (rdEnb == 1'b0) begin
        X_n_offset <= holdData_X_n;
      end
      else begin
        X_n_offset <= rawData_X_n;
      end
    end

  assign #2 X_n_1 = X_n_offset;

  assign snkDonen =  ~ check1_done;



  assign resetn =  ~ reset;



  assign tb_enb = resetn & snkDonen;



  // Delay inside enable generation: register depth 1
  always @(posedge clk or posedge reset)
    begin : u_enable_delay
      if (reset) begin
        tb_enb_delay <= 0;
      end
      else begin
        tb_enb_delay <= tb_enb;
      end
    end

  assign rdEnb = (check1_done == 1'b0 ? tb_enb_delay :
              1'b0);



  assign #2 clk_enable = rdEnb;

  initial
    begin : reset_gen
      reset <= 1'b1;
      # (20);
      @ (posedge clk)
      # (2);
      reset <= 1'b0;
    end

  always 
    begin : clk_gen
      clk <= 1'b1;
      # (5);
      clk <= 1'b0;
      # (5);
      if (check1_done == 1'b1) begin
        clk <= 1'b1;
        # (5);
        clk <= 1'b0;
        # (5);
        $stop;
      end
    end

  DELAY u_DELAY (.clk(clk),
                 .reset(reset),
                 .clk_enable(clk_enable),
                 .X_n(X_n_1),  // uint8
                 .ce_out(ce_out),
                 .X_n_1(X_n_1_1)  // uint8
                 );

  assign X_n_1_enb = ce_out & X_n_1_active;



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 10
  always @(posedge clk or posedge reset)
    begin : c_2_process
      if (reset == 1'b1) begin
        X_n_1_addr <= 4'b0000;
      end
      else begin
        if (X_n_1_enb) begin
          if (X_n_1_addr >= 4'b1010) begin
            X_n_1_addr <= 4'b0000;
          end
          else begin
            X_n_1_addr <= X_n_1_addr + 4'b0001;
          end
        end
      end
    end



  assign X_n_1_lastAddr = X_n_1_addr >= 4'b1010;



  assign X_n_1_done = X_n_1_lastAddr & resetn;



  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_1
      if (reset) begin
        check1_done <= 0;
      end
      else begin
        if (X_n_1_done_enb) begin
          check1_done <= X_n_1_done;
        end
      end
    end

  assign #1 X_n_1_addr_delay_1 = X_n_1_addr;

  // Data source for X_n_1_expected
  initial
    begin : X_n_1_expected_fileread
      fp_X_n_1_expected = $fopen("X_n_1_expected.dat", "r");
      status_X_n_1_expected = $rewind(fp_X_n_1_expected);
    end

  always @(X_n_1_addr_delay_1, ce_out, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        X_n_1_expected <= 8'bx;
      end
      else if (ce_out == 1) begin
        status_X_n_1_expected = $fscanf(fp_X_n_1_expected, "%h", X_n_1_expected);
      end
    end

  assign X_n_1_ref = X_n_1_expected;

  always @(posedge clk or posedge reset)
    begin : X_n_1_1_checker
      if (reset == 1'b1) begin
        X_n_1_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && X_n_1_1 !== X_n_1_ref) begin
          X_n_1_testFailure <= 1'b1;
          $display("ERROR in X_n_1_1 at time %t : Expected '%h' Actual '%h'", $time, X_n_1_ref, X_n_1_1);
        end
      end
    end

  assign testFailure = X_n_1_testFailure;

  always @(posedge clk)
    begin : completed_msg
      if (check1_done == 1'b1) begin
        if (testFailure == 1'b0) begin
          $display("**************TEST COMPLETED (PASSED)**************");
        end
        else begin
          $display("**************TEST COMPLETED (FAILED)**************");
        end
      end
    end

endmodule  // DELAY_tb

